# Generated by Django 5.2.4 on 2025-08-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_address_profile_phone_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='client_satisfaction',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='properties_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='property_types',
            field=models.CharField(blank=True, help_text='Comma-separated list of property types', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='years_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
