# Generated by Django 5.2.4 on 2025-08-02 19:50

import django.db.models.deletion
import multiselectfield.db.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('property_type', models.CharField(choices=[('Flat', 'Flat'), ('Villa', 'Villa'), ('Plot', 'Plot'), ('Commercial', 'Commercial')], max_length=20)),
                ('amenities', multiselectfield.db.fields.MultiSelectField(choices=[('Parking', 'Parking'), ('SwimmingPool', 'SwimmingPool'), ('AirConditioning', 'AirConditioning'), ('Gym', 'Gym')], default=['Parking'], max_length=40)),
                ('bathrooms', models.IntegerField(default=1)),
                ('bedrooms', models.IntegerField(default=1)),
                ('squarefeets', models.DecimalField(decimal_places=3, default=Decimal('100'), max_digits=20)),
                ('type_property', models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale'), ('Lease', 'Lease')], default='Rent', max_length=100)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold'), ('Rented', 'Rented')], default='Available', max_length=20)),
                ('image', models.ImageField(upload_to='property_images/')),
                ('locations', models.CharField(max_length=200)),
                ('zip_code', models.IntegerField(default=1234, max_length=10)),
                ('near_location', models.CharField(default='Near Location', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
